# Generated by Django 3.0 on 2022-10-18 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_Opens', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='hora',
        ),
    ]
