# Generated by Django 4.1.3 on 2022-11-22 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API_Opens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombretabla', models.CharField(max_length=50)),
                ('operacion', models.CharField(max_length=20)),
                ('valoranterior', models.TextField()),
                ('nuevovalor', models.TextField()),
                ('updatedate', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Bitacora',
            },
        ),
        migrations.RemoveField(
            model_name='bitacora_usuario',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bitacora_solicitud',
        ),
        migrations.DeleteModel(
            name='Bitacora_usuario',
        ),
    ]
