# Generated by Django 4.1.3 on 2022-11-23 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_Opens', '0002_bitacora_remove_bitacora_usuario_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bitacora',
            old_name='user',
            new_name='usuario',
        ),
    ]
