# Generated by Django 3.0 on 2022-10-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_Opens', '0002_remove_email_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='fecha',
            field=models.CharField(max_length=50),
        ),
    ]
