# Generated by Django 4.1.3 on 2022-11-23 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_Opens', '0003_rename_user_bitacora_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='usuario',
            field=models.CharField(max_length=20),
        ),
    ]
