# Generated by Django 3.0 on 2022-10-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_Opens', '0004_auto_20221019_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='fecha',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='email',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
