# Generated by Django 3.0 on 2022-10-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_Opens', '0005_auto_20221020_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto_plantilla', models.TextField()),
                ('cuerpo_plantilla', models.TextField()),
            ],
            options={
                'db_table': 'Plantilla',
            },
        ),
    ]
