# Generated by Django 3.0 on 2022-10-27 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API_Opens', '0006_plantilla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abogado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_abogado', models.CharField(max_length=200)),
                ('apellido_abogado', models.CharField(max_length=200)),
                ('fono_abogado', models.CharField(max_length=200)),
                ('direccion_abogado', models.CharField(max_length=200)),
                ('email_abogado', models.CharField(max_length=200)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Abogado',
            },
        ),
        migrations.CreateModel(
            name='Bitacora_usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.DateTimeField()),
                ('detalle_bitacora', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Bitacora_usuario',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField()),
                ('prediccion', models.CharField(max_length=200)),
                ('id_abogado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_Opens.Abogado')),
                ('id_email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_Opens.Email')),
            ],
            options={
                'db_table': 'Solicitud',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_documento', models.DateField()),
                ('solicitud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_Opens.Solicitud')),
            ],
            options={
                'db_table': 'Documento',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('apellido_cliente', models.CharField(max_length=200)),
                ('fono_cliente', models.CharField(max_length=200)),
                ('direccion_cliente', models.CharField(max_length=200)),
                ('id_email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_Opens.Email')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Bitacora_solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField()),
                ('hora_solicitud', models.DateTimeField()),
                ('detalle_solicitud', models.CharField(max_length=200)),
                ('estado_solicitud', models.CharField(max_length=200)),
                ('id_solicitud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_Opens.Solicitud')),
            ],
            options={
                'db_table': 'Bitacora_solicitud',
            },
        ),
    ]
