# Generated by Django 4.1 on 2022-09-01 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abogado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=20)),
                ('apellido', models.CharField(default='', max_length=20)),
                ('fono', models.CharField(default='', max_length=10)),
            ],
            options={
                'db_table': 'Abogado',
            },
        ),
    ]
