# Generated by Django 4.1 on 2022-09-01 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cliente_abogado_direccion_abogado_email_abogado_rut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cliente'),
        ),
    ]
